# Generated by Django 4.2.8 on 2025-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="qr_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
