# Generated by Django 4.2.8 on 2025-10-21 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Slot",
            new_name="TimeSlot",
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
            },
        ),
        migrations.AddField(
            model_name="sport",
            name="duration",
            field=models.IntegerField(
                default=60,
                help_text="Duration in minutes",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="max_players",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of players",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
