# Generated by Django 4.2.8 on 2025-10-23 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_booking_qr_token_player_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(default="Break", max_length=255)),
                ("applies_to_weekdays", models.BooleanField(default=True)),
                ("applies_to_weekends", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_times",
                        to="core.sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Break Time",
                "verbose_name_plural": "Break Times",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="BookingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opens_at", models.TimeField(default="06:00")),
                ("closes_at", models.TimeField(default="22:00")),
                (
                    "slot_duration",
                    models.IntegerField(
                        choices=[
                            (30, "30 minutes"),
                            (60, "1 hour"),
                            (120, "2 hours"),
                            (240, "4 hours"),
                        ],
                        default=60,
                    ),
                ),
                (
                    "advance_booking_days",
                    models.IntegerField(
                        choices=[
                            (1, "1 day"),
                            (3, "3 days"),
                            (7, "7 days"),
                            (15, "15 days"),
                            (30, "30 days"),
                        ],
                        default=7,
                    ),
                ),
                (
                    "min_booking_duration",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_booking_duration",
                    models.IntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "buffer_time",
                    models.IntegerField(
                        default=0,
                        help_text="Buffer time in minutes",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("different_weekend_timings", models.BooleanField(default=False)),
                ("weekend_opens_at", models.TimeField(blank=True, null=True)),
                ("weekend_closes_at", models.TimeField(blank=True, null=True)),
                ("peak_hour_pricing", models.BooleanField(default=False)),
                ("peak_start_time", models.TimeField(blank=True, null=True)),
                ("peak_end_time", models.TimeField(blank=True, null=True)),
                (
                    "peak_price_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("weekend_pricing", models.BooleanField(default=False)),
                (
                    "weekend_price_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_config",
                        to="core.sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Configuration",
                "verbose_name_plural": "Booking Configurations",
            },
        ),
    ]
