# Generated by Django 4.2.8 on 2025-10-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_breaktime_bookingconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackoutDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_dates",
                        to="core.sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blackout Date",
                "verbose_name_plural": "Blackout Dates",
                "ordering": ["date"],
                "unique_together": {("sport", "date")},
            },
        ),
    ]
