# Generated by Django 4.2.8 on 2025-10-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_slot_timeslot_alter_timeslot_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
