# Generated by Django 4.2.8 on 2025-10-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_blackoutdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="blackoutdate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
