# Generated by Django 4.2.8 on 2025-10-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_blackoutdate_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="admin_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
