# Generated by Django 4.2.8 on 2025-10-25 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_admin_disabled_to_timeslot"),
    ]

    operations = []
