# Generated by Django 4.2.8 on 2025-10-25 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20251025_1344"),
    ]

    operations = []
